// ============================================================================
// src/lib/digestApi.ts
//
// What changed since the last snapshot.
//
// Derived rather than stored, so it can't drift from the pages it
// summarises -- a digest disagreeing with the Trading Floor or Physio
// Room would be worse than no digest.
//
// Also the source for scheduled posts. The recommendation there is
// generate-and-queue rather than auto-post: the model will sometimes be
// wrong, and a wrong call published automatically overnight is hard to
// walk back for an account still building credibility.
// ============================================================================

import { supabase } from './supabase';

export type DigestChangeType = 'price_rise' | 'price_fall' | 'availability' | 'ownership';

export type DigestEntry = {
  change_type: DigestChangeType;
  fpl_player_id: number;
  web_name: string;
  slug: string | null;
  team_name: string | null;
  position_label: string;
  ownership: number;
  old_value: string | null;
  new_value: string | null;
  detail: string | null;
  from_date: string;
  to_date: string;
};

export async function getDailyDigest(seasonId = 13): Promise<DigestEntry[]> {
  const { data, error } = await supabase.rpc('get_daily_digest', { p_season_id: seasonId });
  if (error) throw error;
  // change_type is generated by get_daily_digest itself and is one of
  // 'price_rise' | 'price_fall' | 'availability' | 'ownership' (verified
  // against the function's live output). It's plain text to Postgres, so
  // codegen widens it to string.
  return (data ?? []).map((r) => ({
    ...r,
    change_type: r.change_type as DigestChangeType,
    ownership: Number(r.ownership ?? 0),
  }));
}

export const CHANGE_LABELS: Record<DigestChangeType, string> = {
  availability: 'Availability',
  price_rise: 'Price rises',
  price_fall: 'Price falls',
  ownership: 'Ownership swings',
};

/** Display order: availability first because it's the only category
 * that can force a transfer, then prices because they cost money, then
 * ownership which is context rather than a decision. */
export const CHANGE_ORDER: DigestChangeType[] = ['availability', 'price_rise', 'price_fall', 'ownership'];

/** Changes worth pushing at someone, as opposed to everything that
 * moved. A 0.1m move for a 0.3%-owned player is real and irrelevant;
 * the same move at 40% ownership affects most squads.
 *
 * Availability is exempt from the ownership floor: a newly injured
 * player nobody owns yet is exactly the thing worth knowing early. */
export function notable(entries: DigestEntry[], minOwnership = 5): DigestEntry[] {
  return entries.filter((e) => e.change_type === 'availability' || e.ownership >= minOwnership);
}

// ---- A whole gameweek's news ----------------------------------------------
// get_daily_digest only compares the latest snapshot with the one before, so
// yesterday's news vanished every morning. These read the same changes for
// every day of a gameweek, dated, so "In the papers" can keep the news for the
// full gameweek and filter by gameweek. A day belongs to the latest gameweek
// whose deadline fell on an EARLIER date (UK): news seen on deadline day counts
// towards the gameweek before it.

export type GameweekDigestEntry = DigestEntry & { gameweek: number; event_date: string };
export type DigestGameweek = { gameweek: number; first_date: string; last_date: string; days: number };

/** Gameweeks that have news, most recent first. */
export async function getDigestGameweeks(seasonId = 13): Promise<DigestGameweek[]> {
  const { data, error } = await supabase.rpc('get_digest_gameweeks', { p_season_id: seasonId });
  if (error) throw error;
  return (data ?? []).map((r) => ({ gameweek: Number(r.gameweek), first_date: r.first_date, last_date: r.last_date, days: Number(r.days) }));
}

/** Every change in a gameweek (the latest gameweek with news if omitted). */
export async function getGameweekDigest(seasonId = 13, gameweek?: number): Promise<GameweekDigestEntry[]> {
  const { data, error } = await supabase.rpc('get_gameweek_digest', { p_season_id: seasonId, ...(gameweek != null ? { p_gameweek: gameweek } : {}) });
  if (error) throw error;
  return (data ?? []).map((r) => ({
    ...r,
    change_type: r.change_type as DigestChangeType,
    ownership: Number(r.ownership ?? 0),
    gameweek: Number(r.gameweek),
    event_date: r.event_date,
    // kept for DigestEntry compatibility: a gameweek entry is a single day
    from_date: r.event_date,
    to_date: r.event_date,
  })) as GameweekDigestEntry[];
}
