// Generated by scripts/nfl_margin_shape.py -- do not edit by hand.
// Fitted on 2002-2023 (5929 games with a closing line).

/** Spread of the final home margin around the expected margin (points). */
export const MARGIN_SD = 13.259;

/** Key-number weight for each absolute margin 0..30 (observed / normal). */
export const MARGIN_WEIGHTS = [0.093, 0.741, 0.746, 2.813, 0.954, 0.671, 1.231, 1.88, 0.809, 0.348, 1.292, 0.61, 0.419, 0.731, 1.469, 0.494, 0.697, 1.197, 0.912, 0.468, 1.031, 1.405, 0.545, 0.708, 1.495, 0.868, 0.684, 1.215, 1.842, 0.699, 0.798];
