/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.
   The real numbers behind the Nations Cup game: each nation's men's (m)
   and women's (w) strength by surface, from FixtureShark's tennis Elo
   (the mean of its two best active players, half overall Elo, half
   surface Elo). Russia and Belarus are suspended from ITF team events. */
const TEAMS=[
  {"n": "United States", "code": "US", "m": {"hard": 1947, "clay": 1849, "grass": 1901}, "w": {"hard": 2030, "clay": 1975, "grass": 1910}},
  {"n": "Italy", "code": "IT", "m": {"hard": 2075, "clay": 2072, "grass": 2024}, "w": {"hard": 1730, "clay": 1725, "grass": 1706}},
  {"n": "Czechia", "code": "CZ", "m": {"hard": 1856, "clay": 1848, "grass": 1794}, "w": {"hard": 1931, "clay": 1859, "grass": 1910}},
  {"n": "Spain", "code": "ES", "m": {"hard": 2025, "clay": 2069, "grass": 2036}, "w": {"hard": 1727, "clay": 1655, "grass": 1658}},
  {"n": "Poland", "code": "PL", "m": {"hard": 1744, "clay": 1713, "grass": 1778}, "w": {"hard": 1850, "clay": 1905, "grass": 1788}},
  {"n": "Canada", "code": "CA", "m": {"hard": 1844, "clay": 1764, "grass": 1761}, "w": {"hard": 1877, "clay": 1770, "grass": 1733}},
  {"n": "Kazakhstan", "code": "KZ", "m": {"hard": 1734, "clay": 1728, "grass": 1708}, "w": {"hard": 1885, "clay": 1836, "grass": 1791}},
  {"n": "Great Britain", "code": "GB", "m": {"hard": 1849, "clay": 1829, "grass": 1803}, "w": {"hard": 1759, "clay": 1712, "grass": 1729}},
  {"n": "Australia", "code": "AU", "m": {"hard": 1876, "clay": 1830, "grass": 1848}, "w": {"hard": 1690, "clay": 1673, "grass": 1636}},
  {"n": "France", "code": "FR", "m": {"hard": 1875, "clay": 1830, "grass": 1812}, "w": {"hard": 1671, "clay": 1648, "grass": 1644}},
  {"n": "Germany", "code": "DE", "m": {"hard": 1874, "clay": 1890, "grass": 1816}, "w": {"hard": 1647, "clay": 1635, "grass": 1597}},
  {"n": "Serbia", "code": "RS", "m": {"hard": 1871, "clay": 1885, "grass": 1859}, "w": {"hard": 1587, "clay": 1600, "grass": 1577}},
  {"n": "Japan", "code": "JP", "m": {"hard": 1662, "clay": 1679, "grass": 1684}, "w": {"hard": 1749, "clay": 1723, "grass": 1717}},
  {"n": "Switzerland", "code": "CH", "m": {"hard": 1682, "clay": 1637, "grass": 1642}, "w": {"hard": 1766, "clay": 1769, "grass": 1693}},
  {"n": "Argentina", "code": "AR", "m": {"hard": 1794, "clay": 1820, "grass": 1751}, "w": {"hard": 1540, "clay": 1628, "grass": 1575}},
  {"n": "China", "code": "CN", "m": {"hard": 1671, "clay": 1599, "grass": 1639}, "w": {"hard": 1775, "clay": 1723, "grass": 1678}},
  {"n": "Croatia", "code": "HR", "m": {"hard": 1699, "clay": 1733, "grass": 1762}, "w": {"hard": 1623, "clay": 1621, "grass": 1623}},
  {"n": "Belgium", "code": "BE", "m": {"hard": 1713, "clay": 1730, "grass": 1651}, "w": {"hard": 1650, "clay": 1622, "grass": 1668}},
  {"n": "Brazil", "code": "BR", "m": {"hard": 1752, "clay": 1743, "grass": 1698}, "w": {"hard": 1489, "clay": 1557, "grass": 1562}},
  {"n": "Hungary", "code": "HU", "m": {"hard": 1683, "clay": 1682, "grass": 1688}, "w": {"hard": 1565, "clay": 1649, "grass": 1521}},
  {"n": "Netherlands", "code": "NL", "m": {"hard": 1749, "clay": 1695, "grass": 1686}, "w": {"hard": 1533, "clay": 1554, "grass": 1501}},
  {"n": "Greece", "code": "GR", "m": {"hard": 1646, "clay": 1686, "grass": 1621}, "w": {"hard": 1599, "clay": 1593, "grass": 1569}},
  {"n": "Austria", "code": "AT", "m": {"hard": 1566, "clay": 1636, "grass": 1620}, "w": {"hard": 1565, "clay": 1580, "grass": 1565}},
  {"n": "Bulgaria", "code": "BG", "m": {"hard": 1659, "clay": 1641, "grass": 1646}, "w": {"hard": 1490, "clay": 1480, "grass": 1479}}
];
