// ============================================================================
// Shark Fantasy Phase 2: offline simulation prototype.
//
//   npx tsx scripts/sf/sim-season.ts [worlds=40] [seasons=25] [--report path]
//
// Generates worlds, plays whole seasons, and checks the football against
// the calibration targets (src/sharkfantasy/engine/params.ts). Also checks
// reproducibility: the same seed must give byte-identical results.
// Writes a markdown report (default docs/shark-fantasy/calibration.md).
// No database, nothing live.
// ============================================================================
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { calibrate } from '../../src/sharkfantasy/engine/calibrate';
import { generateWorld } from '../../src/sharkfantasy/engine/world';
import { playSeason } from '../../src/sharkfantasy/engine/season';
import { TARGETS, ENGINE_VERSION } from '../../src/sharkfantasy/engine/params';

const args = process.argv.slice(2);
const worlds = Number(args[0] ?? 40), seasons = Number(args[1] ?? 25);
const ri = args.indexOf('--report'), reportPath = ri >= 0 ? args[ri + 1] : 'docs/shark-fantasy/calibration.md';

const t0 = Date.now();
const c = calibrate(worlds, seasons);
const secs = (Date.now() - t0) / 1000;

const hash = (seed: string) => createHash('sha256').update(JSON.stringify(playSeason(generateWorld(seed), 1))).digest('hex');
const reproducible = hash('repro-a') === hash('repro-a') && hash('repro-a') !== hash('repro-b');

const pct = (k: string) => ['homeWin', 'draw', 'nilNil', 'cleanSheetPerTeam', 'goalShareDef', 'goalShareFwd', 'share60', 'favouriteTitleShare'].includes(k);
const fmt = (k: string, v: number) => (pct(k) ? `${(v * 100).toFixed(1)}%` : v.toFixed(2));
const rows = (Object.keys(TARGETS) as (keyof typeof TARGETS)[]).map(k =>
  `| ${k} | ${fmt(k, c.measures[k])} | ${fmt(k, TARGETS[k].value)} ± ${fmt(k, TARGETS[k].tol)} | ${c.pass[k] ? 'pass' : '**FAIL**'} |`);
const sample = playSeason(generateWorld('report-sample'), 1);
const world = generateWorld('report-sample');
const name = (id: string) => world.clubs.find(x => x.id === id)!.name;

const md = `# Shark Fantasy: calibration report

Engine \`${ENGINE_VERSION}\` · ${c.worlds} worlds × ${c.seasons / c.worlds} seasons = ${c.seasons} seasons, ${c.matches.toLocaleString('en-GB')} matches · ${secs.toFixed(0)} s
Generated by \`npx tsx scripts/sf/sim-season.ts ${worlds} ${seasons}\`.

Targets: Premier League 2021/22–2025/26 (FixtureShark \`matches\`, 1,900 matches) and FPL 2023/24–2024/25 player history.

| Measure | Simulated | Target | |
|---|---|---|---|
${rows.join('\n')}

**All targets: ${c.allPass ? 'pass' : 'NOT ALL PASS'}** · Reproducible (same seed, identical bytes): **${reproducible ? 'yes' : 'NO'}**

Fantasy points per appearance (scoring v1; FPL 2023/24–24/25 for comparison GK 3.39, DEF 2.70, MID 2.92, FWD 3.63): ${Object.entries(c.pointsPerApp).map(([k, v]) => `${k} ${v.toFixed(2)}`).join(', ')}

League titles by pre-season strength rank (1 = strongest XI): ${c.titleByStrengthRank.map((v, i) => `${i + 1}: ${(v * 100).toFixed(0)}%`).join(' · ')}

## A sample season (seed \`report-sample\`)

| | Club | P | W | D | L | GF | GA | Pts |
|---|---|---|---|---|---|---|---|---|
${sample.leagueTable.map((r, i) => `| ${i + 1} | ${name(r.clubId)} | ${r.p} | ${r.w} | ${r.d} | ${r.l} | ${r.gf} | ${r.ga} | ${r.pts} |`).join('\n')}

Shark Shield (Finals Sunday): **${name(sample.shieldWinner)}**
`;
mkdirSync(dirname(reportPath), { recursive: true });
writeFileSync(reportPath, md);
console.log(md);
process.exit(c.allPass && reproducible ? 0 : 1);
