"""Write the real numbers each Beat the Shark game uses into a small,
committed data file, so the games never call the database and stay
independent of the analytics site.

    python scripts/beat_the_shark_data.py

World Cup (games/beat-the-shark/world-cup/data.js), needs SUPABASE_DB_URL
(or --nations-json FILE with the rows of NATIONS_SQL):
  - the international model IP1's fitted parameters (intl.model_info);
  - every active FIFA nation's current Elo (intl.team_summary), top 48.

Nations Cup (games/beat-the-shark/nations-cup/data.js), needs SUPABASE_DB_URL
(or --nations-json FILE with the rows of TENNIS_SQL):
    python scripts/beat_the_shark_data.py nations-cup
  - each nation's men's and women's strength on hard, clay and grass, from
    the tennis Elo ratings (tennis.player_ratings) and players' countries.

NFL (games/beat-the-shark/nfl/data.js):
  - home edge: the live Elo model's HFA (scripts/nfl_elo.py), converted to
    points at 25 Elo points a point, as that model does;
  - the margin spread and key-number weights fitted by
    scripts/nfl_margin_shape.py (src/lib/nflMarginShape.ts).

Re-run after either model is refitted. The game's checks compare its own
match engine with these numbers.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def nfl() -> None:
    elo_src = (ROOT / "scripts" / "nfl_elo.py").read_text(encoding="utf-8")
    m = re.search(r"^K, HFA, REG = (\d+), (\d+), ([\d.]+)", elo_src, re.M)
    if not m:
        raise SystemExit("nfl_elo.py: could not find 'K, HFA, REG = ...'")
    hfa_elo = int(m.group(2))
    shape = (ROOT / "src" / "lib" / "nflMarginShape.ts").read_text(encoding="utf-8")
    sd = float(re.search(r"MARGIN_SD = ([\d.]+)", shape).group(1))
    weights = json.loads(re.search(r"MARGIN_WEIGHTS = (\[[^\]]*\])", shape).group(1))
    out = ROOT / "games" / "beat-the-shark" / "nfl" / "data.js"
    out.write_text(
        "/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.\n"
        "   The real numbers behind the NFL game, from FixtureShark's own models. */\n"
        f"const NFL_DATA={{homeEloPoints:{hfa_elo},homePoints:{hfa_elo / 25:.2f},"
        f"marginSd:{sd},marginWeights:{json.dumps(weights)}}};\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)}: home {hfa_elo} Elo = {hfa_elo / 25:.2f} points, sd {sd}")


NATIONS_SQL = """
select team, slug, confederation, round(elo)::int as elo
from intl.team_summary
where last_match >= current_date - interval '18 months'
  and confederation is not null and slug <> 'russia'  -- banned from FIFA competitions
order by elo desc limit 48"""
PARAMS_SQL = "select params, fitted_through from intl.model_info where model = 'IP1'"


def world_cup(nations_json: str | None = None, params_json: str | None = None) -> None:
    if nations_json:
        nations = json.loads(Path(nations_json).read_text(encoding="utf-8"))
        info = json.loads(Path(params_json).read_text(encoding="utf-8"))
    else:
        import os
        import psycopg  # only needed for a live refresh
        with psycopg.connect(os.environ["SUPABASE_DB_URL"]) as con, con.cursor() as cur:
            cur.execute(NATIONS_SQL)
            nations = [dict(zip(["team", "slug", "confederation", "elo"], r)) for r in cur.fetchall()]
            cur.execute(PARAMS_SQL)
            p, through = cur.fetchone()
            info = {"params": p, "fitted_through": through}
    names = ["mu", "home", "b", "k_qualifying", "k_nations_league", "k_tournament", "rho", "e"]
    ip1 = dict(zip(names, info["params"]))
    out = ROOT / "games" / "beat-the-shark" / "world-cup" / "data.js"
    rows = ",\n  ".join(json.dumps({"n": r["team"], "c": r["confederation"], "elo": int(r["elo"])}, ensure_ascii=False) for r in nations)
    out.write_text(
        "/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.\n"
        "   The real numbers behind the World Cup game: FixtureShark's\n"
        f"   international model IP1 (fitted through {info['fitted_through']}) and the\n"
        "   48 strongest active nations by its Elo. */\n"
        f"const IP1={json.dumps({k: round(v, 6) for k, v in ip1.items()})};\n"
        f"const NATIONS=[\n  {rows}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)}: {len(nations)} nations, top {nations[0]['team']} {nations[0]['elo']}")


TENNIS_SQL = """
with act as (
  select p.tour, pp.country, r.player_id,
    max(r.rating) filter (where surface = 'All') a,
    max(r.rating) filter (where surface = 'Hard') h,
    max(r.rating) filter (where surface = 'Clay') c,
    max(r.rating) filter (where surface = 'Grass') g,
    max(r.last_match) filter (where surface = 'All') lm
  from tennis.player_ratings r join tennis.players p using (player_id)
  join tennis.player_people pp using (player_id)
  group by 1, 2, 3)
, ranked as (select *, row_number() over (partition by tour, country order by a desc) rn
  from act where lm >= current_date - 365 and country is not null
    and country not in ('RU', 'BY'))  -- suspended from ITF team events
, nat as (select country, tour,
   round(avg((a + coalesce(h, a)) / 2))::int h, round(avg((a + coalesce(c, a)) / 2))::int c,
   round(avg((a + coalesce(g, a)) / 2))::int g
  from ranked where rn <= 2 group by 1, 2 having count(*) = 2)
select m.country, m.h mh, m.c mc, m.g mg, w.h wh, w.c wc, w.g wg
from nat m join nat w on w.country = m.country and w.tour = 'WTA' where m.tour = 'ATP'
order by (m.h + m.c + m.g + w.h + w.c + w.g) desc limit 24"""
COUNTRY_NAMES = {
    "US": "United States", "IT": "Italy", "CZ": "Czechia", "ES": "Spain", "PL": "Poland", "CA": "Canada",
    "KZ": "Kazakhstan", "GB": "Great Britain", "AU": "Australia", "FR": "France", "DE": "Germany",
    "RS": "Serbia", "JP": "Japan", "CH": "Switzerland", "AR": "Argentina", "CN": "China", "HR": "Croatia",
    "BE": "Belgium", "BR": "Brazil", "HU": "Hungary", "NL": "Netherlands", "GR": "Greece", "AT": "Austria",
    "BG": "Bulgaria", "SE": "Sweden", "IN": "India", "UA": "Ukraine", "RO": "Romania", "DK": "Denmark",
    "NO": "Norway", "PT": "Portugal", "CL": "Chile", "LV": "Latvia", "SK": "Slovakia",
}


def nations_cup(nations_json: str | None = None) -> None:
    """Nations Cup (games/beat-the-shark/nations-cup/data.js): each nation's
    men's and women's strength on hard, clay and grass. A nation's strength
    on a surface is the mean of its two best active players (a match in the
    last year) by overall Elo, each rated half overall Elo and half surface
    Elo (tennis.player_ratings), as the head-to-head model weighs both."""
    if nations_json:
        rows = json.loads(Path(nations_json).read_text(encoding="utf-8"))
    else:
        import os
        import psycopg
        with psycopg.connect(os.environ["SUPABASE_DB_URL"]) as con, con.cursor() as cur:
            cur.execute(TENNIS_SQL)
            rows = [dict(zip(["country", "mh", "mc", "mg", "wh", "wc", "wg"], r)) for r in cur.fetchall()]
    rows = rows[:24]
    missing = [r["country"] for r in rows if r["country"] not in COUNTRY_NAMES]
    if missing:
        raise SystemExit(f"add names for: {missing}")
    out = ROOT / "games" / "beat-the-shark" / "nations-cup" / "data.js"
    body = ",\n  ".join(
        json.dumps({"n": COUNTRY_NAMES[r["country"]], "code": r["country"],
                    "m": {"hard": r["mh"], "clay": r["mc"], "grass": r["mg"]},
                    "w": {"hard": r["wh"], "clay": r["wc"], "grass": r["wg"]}}, ensure_ascii=False)
        for r in rows)
    out.write_text(
        "/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.\n"
        "   The real numbers behind the Nations Cup game: each nation's men's (m)\n"
        "   and women's (w) strength by surface, from FixtureShark's tennis Elo\n"
        "   (the mean of its two best active players, half overall Elo, half\n"
        "   surface Elo). Russia and Belarus are suspended from ITF team events. */\n"
        f"const TEAMS=[\n  {body}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)}: {len(rows)} nations, top {COUNTRY_NAMES[rows[0]['country']]}")


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "nations-cup":
        a = sys.argv[2:]
        nations_cup(a[a.index("--nations-json") + 1] if "--nations-json" in a else None)
    elif len(sys.argv) > 1 and sys.argv[1] == "world-cup":
        a = sys.argv[2:]
        world_cup(*(a[a.index("--nations-json") + 1:a.index("--nations-json") + 2] + a[a.index("--params-json") + 1:a.index("--params-json") + 2]) if "--nations-json" in a else ())
    else:
        nfl()
