"""Write the real numbers each Beat the Shark game uses into a small,
committed data file, so the games never call the database and stay
independent of the analytics site.

    python scripts/beat_the_shark_data.py

NFL (games/beat-the-shark/nfl/data.js):
  - home edge: the live Elo model's HFA (scripts/nfl_elo.py), converted to
    points at 25 Elo points a point, as that model does;
  - the margin spread and key-number weights fitted by
    scripts/nfl_margin_shape.py (src/lib/nflMarginShape.ts).

Re-run after either model is refitted. The game's checks compare its own
match engine with these numbers.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def nfl() -> None:
    elo_src = (ROOT / "scripts" / "nfl_elo.py").read_text(encoding="utf-8")
    m = re.search(r"^K, HFA, REG = (\d+), (\d+), ([\d.]+)", elo_src, re.M)
    if not m:
        raise SystemExit("nfl_elo.py: could not find 'K, HFA, REG = ...'")
    hfa_elo = int(m.group(2))
    shape = (ROOT / "src" / "lib" / "nflMarginShape.ts").read_text(encoding="utf-8")
    sd = float(re.search(r"MARGIN_SD = ([\d.]+)", shape).group(1))
    weights = json.loads(re.search(r"MARGIN_WEIGHTS = (\[[^\]]*\])", shape).group(1))
    out = ROOT / "games" / "beat-the-shark" / "nfl" / "data.js"
    out.write_text(
        "/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.\n"
        "   The real numbers behind the NFL game, from FixtureShark's own models. */\n"
        f"const NFL_DATA={{homeEloPoints:{hfa_elo},homePoints:{hfa_elo / 25:.2f},"
        f"marginSd:{sd},marginWeights:{json.dumps(weights)}}};\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)}: home {hfa_elo} Elo = {hfa_elo / 25:.2f} points, sd {sd}")


if __name__ == "__main__":
    nfl()
