"""Write the real numbers each Beat the Shark game uses into a small,
committed data file, so the games never call the database and stay
independent of the analytics site.

    python scripts/beat_the_shark_data.py

World Cup (games/beat-the-shark/world-cup/data.js), needs SUPABASE_DB_URL
(or --nations-json FILE with the rows of NATIONS_SQL):
  - the international model IP1's fitted parameters (intl.model_info);
  - every active FIFA nation's current Elo (intl.team_summary), top 48.

NFL (games/beat-the-shark/nfl/data.js):
  - home edge: the live Elo model's HFA (scripts/nfl_elo.py), converted to
    points at 25 Elo points a point, as that model does;
  - the margin spread and key-number weights fitted by
    scripts/nfl_margin_shape.py (src/lib/nflMarginShape.ts).

Re-run after either model is refitted. The game's checks compare its own
match engine with these numbers.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def nfl() -> None:
    elo_src = (ROOT / "scripts" / "nfl_elo.py").read_text(encoding="utf-8")
    m = re.search(r"^K, HFA, REG = (\d+), (\d+), ([\d.]+)", elo_src, re.M)
    if not m:
        raise SystemExit("nfl_elo.py: could not find 'K, HFA, REG = ...'")
    hfa_elo = int(m.group(2))
    shape = (ROOT / "src" / "lib" / "nflMarginShape.ts").read_text(encoding="utf-8")
    sd = float(re.search(r"MARGIN_SD = ([\d.]+)", shape).group(1))
    weights = json.loads(re.search(r"MARGIN_WEIGHTS = (\[[^\]]*\])", shape).group(1))
    out = ROOT / "games" / "beat-the-shark" / "nfl" / "data.js"
    out.write_text(
        "/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.\n"
        "   The real numbers behind the NFL game, from FixtureShark's own models. */\n"
        f"const NFL_DATA={{homeEloPoints:{hfa_elo},homePoints:{hfa_elo / 25:.2f},"
        f"marginSd:{sd},marginWeights:{json.dumps(weights)}}};\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)}: home {hfa_elo} Elo = {hfa_elo / 25:.2f} points, sd {sd}")


NATIONS_SQL = """
select team, slug, confederation, round(elo)::int as elo
from intl.team_summary
where last_match >= current_date - interval '18 months'
  and confederation is not null and slug <> 'russia'  -- banned from FIFA competitions
order by elo desc limit 48"""
PARAMS_SQL = "select params, fitted_through from intl.model_info where model = 'IP1'"


def world_cup(nations_json: str | None = None, params_json: str | None = None) -> None:
    if nations_json:
        nations = json.loads(Path(nations_json).read_text(encoding="utf-8"))
        info = json.loads(Path(params_json).read_text(encoding="utf-8"))
    else:
        import os
        import psycopg  # only needed for a live refresh
        with psycopg.connect(os.environ["SUPABASE_DB_URL"]) as con, con.cursor() as cur:
            cur.execute(NATIONS_SQL)
            nations = [dict(zip(["team", "slug", "confederation", "elo"], r)) for r in cur.fetchall()]
            cur.execute(PARAMS_SQL)
            p, through = cur.fetchone()
            info = {"params": p, "fitted_through": through}
    names = ["mu", "home", "b", "k_qualifying", "k_nations_league", "k_tournament", "rho", "e"]
    ip1 = dict(zip(names, info["params"]))
    out = ROOT / "games" / "beat-the-shark" / "world-cup" / "data.js"
    rows = ",\n  ".join(json.dumps({"n": r["team"], "c": r["confederation"], "elo": int(r["elo"])}, ensure_ascii=False) for r in nations)
    out.write_text(
        "/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.\n"
        "   The real numbers behind the World Cup game: FixtureShark's\n"
        f"   international model IP1 (fitted through {info['fitted_through']}) and the\n"
        "   48 strongest active nations by its Elo. */\n"
        f"const IP1={json.dumps({k: round(v, 6) for k, v in ip1.items()})};\n"
        f"const NATIONS=[\n  {rows}\n];\n",
        encoding="utf-8",
    )
    print(f"wrote {out.relative_to(ROOT)}: {len(nations)} nations, top {nations[0]['team']} {nations[0]['elo']}")


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "world-cup":
        a = sys.argv[2:]
        world_cup(*(a[a.index("--nations-json") + 1:a.index("--nations-json") + 2] + a[a.index("--params-json") + 1:a.index("--params-json") + 2]) if "--nations-json" in a else ())
    else:
        nfl()
