#!/usr/bin/env python3
# ============================================================================
# scripts/nfl_margin_shape.py
#
# Fits the shape of NFL final margins around an expected margin, and writes
# src/lib/nflMarginShape.ts for the game page's "likely margins" chart.
#
# The model (Stern 1991, "On the probability of winning a football game",
# The American Statistician 45(3)): the home margin is roughly Normal(mu, sd)
# around the expected margin. NFL scores come in 3s and 7s, so real margins
# bunch on "key numbers" (3, 7, 10, 14, 17 ...) that a smooth curve misses.
# Each absolute margin k gets a weight w(k) = observed / expected, where
# expected comes from the discretised normal around every game's closing
# spread; the page multiplies the normal by w and renormalises.
#
# Fitted on 2002-2023 (the Model Lab tuning seasons); 2024 (validation) is
# the check -- mean log loss of the exact margin, normal v weighted. 2025+
# (the sealed holdout) is never read. Weights past 30 points are too noisy
# to keep and are left at 1.
#
#   python scripts/nfl_margin_shape.py            # fit, check, write the .ts
#   python scripts/nfl_margin_shape.py --games games.csv   # from a local copy
# ============================================================================

import argparse
import csv
import math
import statistics
import io
import urllib.request
from collections import Counter
from pathlib import Path

GAMES_URL = "https://raw.githubusercontent.com/nflverse/nfldata/master/data/games.csv"  # as nfl_import.py


def fetch_csv(url: str) -> list[dict]:
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": "fixtureshark"}), timeout=60) as r:
        return list(csv.DictReader(io.StringIO(r.read().decode("utf-8"))))

FIT = range(2002, 2024)
CHECK = 2024
KMAX = 30
OUT = Path(__file__).parent.parent / "src" / "lib" / "nflMarginShape.ts"


def phi(x: float) -> float:
    return 0.5 * (1 + math.erf(x / math.sqrt(2)))


def p_normal(m: int, mu: float, sd: float) -> float:
    return phi((m + 0.5 - mu) / sd) - phi((m - 0.5 - mu) / sd)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--games", help="local games.csv (default: nflverse)")
    args = ap.parse_args()
    rows = list(csv.DictReader(open(args.games))) if args.games else fetch_csv(GAMES_URL)
    rows = [g for g in rows if g["home_score"] not in ("", "NA") and g["spread_line"] not in ("", "NA")]
    margin = lambda g: int(g["home_score"]) - int(g["away_score"])  # noqa: E731
    fit = [g for g in rows if int(g["season"]) in FIT]
    check = [g for g in rows if int(g["season"]) == CHECK]

    sd = statistics.pstdev([margin(g) - float(g["spread_line"]) for g in fit])
    obs, exp = Counter(), Counter()
    for g in fit:
        obs[abs(margin(g))] += 1
        mu = float(g["spread_line"])
        for k in range(-90, 91):
            exp[abs(k)] += p_normal(k, mu, sd)
    w = [round((obs[k] + 1) / (exp[k] + 1), 3) for k in range(KMAX + 1)]

    def dist(mu: float, weighted: bool) -> dict[int, float]:
        p = {k: p_normal(k, mu, sd) * (w[abs(k)] if weighted and abs(k) <= KMAX else 1) for k in range(-90, 91)}
        z = sum(p.values())
        return {k: v / z for k, v in p.items()}

    for weighted in (False, True):
        ll = statistics.mean(-math.log(dist(float(g["spread_line"]), weighted)[margin(g)]) for g in check)
        print(f"{CHECK} exact-margin log loss, {'key-number weighted' if weighted else 'plain normal'}: {ll:.4f} ({len(check)} games)")
    print(f"fit: {len(fit)} games, sd {sd:.2f}")

    OUT.write_text(
        "// Generated by scripts/nfl_margin_shape.py -- do not edit by hand.\n"
        f"// Fitted on {FIT.start}-{FIT.stop - 1} ({len(fit)} games with a closing line).\n\n"
        "/** Spread of the final home margin around the expected margin (points). */\n"
        f"export const MARGIN_SD = {sd:.3f};\n\n"
        "/** Key-number weight for each absolute margin 0..30 (observed / normal). */\n"
        f"export const MARGIN_WEIGHTS = [{', '.join(str(x) for x in w)}];\n"
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
