/* Generated by scripts/beat_the_shark_data.py -- do not edit by hand.
   The real numbers behind the NFL game, from FixtureShark's own models. */
const NFL_DATA={homeEloPoints:45,homePoints:1.80,marginSd:13.259,marginWeights:[0.093, 0.741, 0.746, 2.813, 0.954, 0.671, 1.231, 1.88, 0.809, 0.348, 1.292, 0.61, 0.419, 0.731, 1.469, 0.494, 0.697, 1.197, 0.912, 0.468, 1.031, 1.405, 0.545, 0.708, 1.495, 0.868, 0.684, 1.215, 1.842, 0.699, 0.798]};
